apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server
spec:
  # Replace with older version. Due to below error:
  ## Build Failed: admission webhook "elastic-apm-validation-v1.k8s.elastic.co" denied the request: ApmServer.apm.k8s.elastic.co "apm-server" is invalid: spec.version: Invalid value: "9.1.0-5859ff16-SNAPSHOT": Unsupported version: version 9.1.0-5859ff16-SNAPSHOT is higher than the highest supported version of 8.99.99
  version: 8.16.0-bff94f3c-SNAPSHOT
  count: 1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  config:
    apm-server:
      pprof:
        enabled: true
      expvar:
        enabled: true
    logging:
      level: debug
    monitoring:
      enabled: true
      elasticsearch:
        username: admin
        password: changeme
        hosts: [http://elasticsearch-es-http.default.svc:9200]
        protocol: "http"
    output:
      elasticsearch:
        username: admin
        password: changeme
  elasticsearchRef:
    name: elasticsearch
    namespace: default
  podTemplate:
    spec:
      containers:
        - name: apm-server
          resources:
            limits:
              cpu: 1
              memory: "2Gi"
            requests:
              cpu: 1
              memory: "1Gi"
